name: Full Test

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install core
        run: pip install pydantic injector starlette
      - name: Install tests
        run: pip install pytest pytest-asyncio
      - name: Test
        run: pytest

  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Black
        run: black --check architek tests
      - name: isort
        run: isort --check architek tests
      - name: Flake8
        run: flake8 architek tests
      - name: mypy
        run: mypy architek
